---
http_interactions:
- request:
    method: get
    uri: https://api.lokalise.com/api2/projects/8812905263134de7bdcd51.85515837
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      User-Agent:
      - ruby-client
      X-Api-Token:
      - "<LOKALISE_API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Sat, 03 Sep 2022 13:25:34 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Server:
      - nginx
      Vary:
      - Accept-Encoding
      Cache-Control:
      - max-age=0, must-revalidate, no-cache, no-store, private
      Pragma:
      - no-cache
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - deny
      X-Xss-Protection:
      - 1; mode=block
      Strict-Transport-Security:
      - max-age=31536000
      Referrer-Policy:
      - origin
      X-Lokalise-Process-Id:
      - 170e493f-94a4-462d-a3f7-b9778496dc74
      Expires:
      - Sat, 03 Sep 2022 13:25:34 GMT
      Set-Cookie:
      - PHPSESSID=deleted; expires=Fri, 03-Sep-2021 13:25:33 GMT; Max-Age=0; path=/;
        httponly
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Headers:
      - Content-Type
    body:
      encoding: ASCII-8BIT
      string: '{"project_id":"8812905263134de7bdcd51.85515837","project_type":"localization_files","name":"\u041c\u0430\u043a\u0441\u0438\u043c
        \u041a\u043b\u0438\u043c\u043e\u0432\u0438\u0447\u2019s first project","description":"","created_at":"2022-09-03
        12:51:51 (Etc\/UTC)","created_at_timestamp":1662209511,"created_by":211944,"created_by_email":"maks.762373maksim@gmail.com","team_id":334114,"base_language_id":640,"base_language_iso":"en","settings":{"per_platform_key_names":false,"reviewing":true,"upvoting":false,"auto_toggle_unverified":true,"offline_translation":false,"key_editing":true,"inline_machine_translations":true,"branching":false,"segmentation":false,"custom_translation_statuses":false,"custom_translation_statuses_allow_multiple":false},"statistics":{"progress_total":0,"keys_total":0,"team":1,"base_words":0,"qa_issues_total":0,"qa_issues":{"not_reviewed":0,"unverified":0,"spelling_grammar":0,"inconsistent_placeholders":0,"inconsistent_html":0,"different_number_of_urls":0,"different_urls":0,"leading_whitespace":0,"trailing_whitespace":0,"different_number_of_email_address":0,"different_email_address":0,"different_brackets":0,"different_numbers":0,"double_space":0,"special_placeholder":0,"unbalanced_brackets":0},"languages":[{"language_id":640,"language_iso":"en","progress":0,"words_to_do":0},{"language_id":597,"language_iso":"ru","progress":0,"words_to_do":0}]}}'
  recorded_at: Sat, 03 Sep 2022 13:25:34 GMT
recorded_with: VCR 6.1.0
